let mockJobsData = [
  {
    company: 'Bechtelar-Bednar',
    position: 'Civil Engineer',
    status: 'declined',
    jobType: 'internship',
    jobLocation: 'Kiamba',
  },
  {
    company: 'Kunze and Sons',
    position: 'Accounting Assistant III',
    status: 'interview',
    jobType: 'remote',
    jobLocation: 'Kafr Mandā',
  },
  {
    company: 'Cremin LLC',
    position: 'Environmental Tech',
    status: 'declined',
    jobType: 'full-time',
    jobLocation: 'Meixian',
  },
  {
    company: 'Klocko and Sons',
    position: 'Actuary',
    status: 'pending',
    jobType: 'full-time',
    jobLocation: 'Dianfang',
  },
  {
    company: 'Mraz-Hilpert',
    position: 'Account Executive',
    status: 'pending',
    jobType: 'full-time',
    jobLocation: 'Kota Kinabalu',
  },
  {
    company: 'Little LLC',
    position: 'Dental Hygienist',
    status: 'declined',
    jobType: 'remote',
    jobLocation: 'Rebrikha',
  },
  {
    company: 'Barrows Inc',
    position: 'Graphic Designer',
    status: 'interview',
    jobType: 'internship',
    jobLocation: 'Baihua',
  },
  {
    company: 'Schimmel, Beahan and Baumbach',
    position: 'Pharmacist',
    status: 'interview',
    jobType: 'internship',
    jobLocation: 'Jakhaly',
  },
  {
    company: 'Stehr, Homenick and Turcotte',
    position: 'Assistant Professor',
    status: 'interview',
    jobType: 'full-time',
    jobLocation: 'Shizi',
  },
  {
    company: 'Fritsch-Muller',
    position: 'Desktop Support Technician',
    status: 'declined',
    jobType: 'remote',
    jobLocation: 'Kosai-shi',
  },
  {
    company: 'Marvin-Wisoky',
    position: 'Nuclear Power Engineer',
    status: 'interview',
    jobType: 'part-time',
    jobLocation: 'Sulkava',
  },
  {
    company: 'Schmitt, Murphy and Simonis',
    position: 'Staff Scientist',
    status: 'declined',
    jobType: 'internship',
    jobLocation: 'Puntaru',
  },
  {
    company: 'Hills, Ward and Gleichner',
    position: 'Senior Editor',
    status: 'pending',
    jobType: 'part-time',
    jobLocation: 'Giồng Riềng',
  },
  {
    company: 'Macejkovic Group',
    position: 'Executive Secretary',
    status: 'interview',
    jobType: 'full-time',
    jobLocation: 'Piracuruca',
  },
  {
    company: 'Littel, Cummerata and Wisoky',
    position: 'Accounting Assistant III',
    status: 'pending',
    jobType: 'remote',
    jobLocation: 'Simitli',
  },
  {
    company: 'Rutherford-Considine',
    position: 'Chemical Engineer',
    status: 'declined',
    jobType: 'remote',
    jobLocation: 'Sukosari',
  },
  {
    company: 'Runolfsdottir and Sons',
    position: 'Associate Professor',
    status: 'interview',
    jobType: 'full-time',
    jobLocation: 'Hewan',
  },
  {
    company: 'Hahn-Koss',
    position: 'Clinical Specialist',
    status: 'pending',
    jobType: 'part-time',
    jobLocation: 'Tiancheng',
  },
  {
    company: 'Wilkinson-Kub',
    position: 'Automation Specialist II',
    status: 'declined',
    jobType: 'remote',
    jobLocation: 'Kuznetsovs’k',
  },
  {
    company: 'Klein, Wunsch and Gutmann',
    position: 'Clinical Specialist',
    status: 'interview',
    jobType: 'full-time',
    jobLocation: 'Neiguan',
  },
  {
    company: 'Shanahan-Runte',
    position: 'Developer III',
    status: 'pending',
    jobType: 'remote',
    jobLocation: 'Liuhe',
  },
  {
    company: 'Crooks-Dare',
    position: 'Librarian',
    status: 'interview',
    jobType: 'internship',
    jobLocation: 'Lévis',
  },
  {
    company: 'Bednar-Osinski',
    position: 'Chief Design Engineer',
    status: 'pending',
    jobType: 'part-time',
    jobLocation: 'Langley',
  },
  {
    company: 'Gislason, Rice and Rosenbaum',
    position: 'Help Desk Operator',
    status: 'pending',
    jobType: 'part-time',
    jobLocation: 'As Suwaydā',
  },
  {
    company: 'Grimes, Cormier and Funk',
    position: 'Systems Administrator II',
    status: 'interview',
    jobType: 'full-time',
    jobLocation: 'Levashi',
  },
  {
    company: 'Bode, Bernier and Trantow',
    position: 'Database Administrator II',
    status: 'pending',
    jobType: 'full-time',
    jobLocation: 'San Agustin',
  },
  {
    company: 'Smitham Inc',
    position: 'Programmer Analyst I',
    status: 'declined',
    jobType: 'internship',
    jobLocation: 'Shanghu',
  },
  {
    company: 'Roob and Sons',
    position: 'Assistant Professor',
    status: 'declined',
    jobType: 'full-time',
    jobLocation: 'Kebonsari Kidul',
  },
  {
    company: 'Kreiger, Thiel and McDermott',
    position: 'Geologist IV',
    status: 'declined',
    jobType: 'remote',
    jobLocation: 'Cerenti',
  },
  {
    company: 'Wiza, Sawayn and Hayes',
    position: 'Legal Assistant',
    status: 'declined',
    jobType: 'part-time',
    jobLocation: 'Rio Pardo',
  },
  {
    company: 'Boehm, Bashirian and Ledner',
    position: 'Internal Auditor',
    status: 'interview',
    jobType: 'part-time',
    jobLocation: 'Princeton',
  },
  {
    company: 'West-Cruickshank',
    position: 'Assistant Media Planner',
    status: 'pending',
    jobType: 'full-time',
    jobLocation: 'San Ramón de la Nueva Orán',
  },
  {
    company: 'Bode Group',
    position: 'Quality Control Specialist',
    status: 'declined',
    jobType: 'full-time',
    jobLocation: 'Kosaya Gora',
  },
  {
    company: 'Predovic and Sons',
    position: 'Senior Financial Analyst',
    status: 'pending',
    jobType: 'part-time',
    jobLocation: 'Estoi',
  },
  {
    company: 'Waters-Koch',
    position: 'Help Desk Operator',
    status: 'pending',
    jobType: 'full-time',
    jobLocation: 'Orsha',
  },
  {
    company: 'Kirlin LLC',
    position: 'Software Test Engineer IV',
    status: 'interview',
    jobType: 'remote',
    jobLocation: 'Isulan',
  },
  {
    company: 'Koch Group',
    position: 'Web Designer III',
    status: 'pending',
    jobType: 'internship',
    jobLocation: 'San Miguel',
  },
  {
    company: 'Pacocha and Sons',
    position: 'Tax Accountant',
    status: 'interview',
    jobType: 'part-time',
    jobLocation: 'An Lão',
  },
  {
    company: 'Weber, Glover and Quitzon',
    position: 'Electrical Engineer',
    status: 'declined',
    jobType: 'internship',
    jobLocation: 'København',
  },
  {
    company: 'Veum-Kulas',
    position: 'Marketing Assistant',
    status: 'pending',
    jobType: 'internship',
    jobLocation: 'Guohe',
  },
  {
    company: 'Luettgen, Swaniawski and Altenwerth',
    position: 'Human Resources Manager',
    status: 'interview',
    jobType: 'part-time',
    jobLocation: 'Fengmen',
  },
  {
    company: 'Jaskolski LLC',
    position: 'Physical Therapy Assistant',
    status: 'interview',
    jobType: 'part-time',
    jobLocation: 'Paoua',
  },
  {
    company: 'Bins-Ullrich',
    position: 'Dental Hygienist',
    status: 'interview',
    jobType: 'internship',
    jobLocation: 'Methven',
  },
  {
    company: 'Price Inc',
    position: 'Cost Accountant',
    status: 'interview',
    jobType: 'remote',
    jobLocation: 'Severnyy',
  },
  {
    company: 'Windler-Turner',
    position: 'Research Nurse',
    status: 'interview',
    jobType: 'part-time',
    jobLocation: 'Tilburg',
  },
  {
    company: "Runte-O'Reilly",
    position: 'Tax Accountant',
    status: 'interview',
    jobType: 'part-time',
    jobLocation: 'Chok Chai',
  },
  {
    company: 'Kunde and Sons',
    position: 'Sales Associate',
    status: 'declined',
    jobType: 'internship',
    jobLocation: 'La Mesa',
  },
  {
    company: 'Borer, Dibbert and Larson',
    position: 'Community Outreach Specialist',
    status: 'interview',
    jobType: 'remote',
    jobLocation: 'Svislach',
  },
  {
    company: 'Heathcote, Herzog and Konopelski',
    position: 'Biostatistician IV',
    status: 'interview',
    jobType: 'full-time',
    jobLocation: 'Dingzhai',
  },
  {
    company: 'Satterfield Group',
    position: 'Nuclear Power Engineer',
    status: 'pending',
    jobType: 'remote',
    jobLocation: 'Si Bun Rueang',
  },
  {
    company: 'Toy Group',
    position: 'Software Consultant',
    status: 'interview',
    jobType: 'full-time',
    jobLocation: 'Belfast',
  },
  {
    company: 'Schumm-Cormier',
    position: 'Programmer Analyst I',
    status: 'pending',
    jobType: 'remote',
    jobLocation: 'New Agutaya',
  },
  {
    company: 'Labadie LLC',
    position: 'Account Representative II',
    status: 'pending',
    jobType: 'remote',
    jobLocation: 'Paripiranga',
  },
  {
    company: 'Strosin and Sons',
    position: 'Staff Accountant II',
    status: 'interview',
    jobType: 'remote',
    jobLocation: 'Gnosjö',
  },
  {
    company: 'Swaniawski-Murphy',
    position: 'Web Designer IV',
    status: 'interview',
    jobType: 'remote',
    jobLocation: 'Liutan',
  },
  {
    company: 'Kuhlman, Balistreri and Romaguera',
    position: 'Automation Specialist I',
    status: 'declined',
    jobType: 'remote',
    jobLocation: 'Utmānzai',
  },
  {
    company: 'Erdman and Sons',
    position: 'Civil Engineer',
    status: 'pending',
    jobType: 'remote',
    jobLocation: 'Arrah',
  },
  {
    company: 'Senger-Greenfelder',
    position: 'Payment Adjustment Coordinator',
    status: 'declined',
    jobType: 'internship',
    jobLocation: 'Verkhozim',
  },
  {
    company: 'Rutherford-Brown',
    position: 'Chief Design Engineer',
    status: 'declined',
    jobType: 'remote',
    jobLocation: 'Fulong',
  },
  {
    company: 'Cartwright LLC',
    position: 'Engineer IV',
    status: 'declined',
    jobType: 'internship',
    jobLocation: 'Pétionville',
  },
  {
    company: 'Turcotte and Sons',
    position: 'Research Assistant IV',
    status: 'pending',
    jobType: 'full-time',
    jobLocation: 'Būrabay',
  },
  {
    company: 'Raynor, Harber and Boyer',
    position: 'Programmer I',
    status: 'declined',
    jobType: 'remote',
    jobLocation: 'Cartagena',
  },
  {
    company: 'Rohan-Feil',
    position: 'Programmer II',
    status: 'pending',
    jobType: 'full-time',
    jobLocation: 'Lidköping',
  },
  {
    company: 'Kirlin LLC',
    position: 'Developer IV',
    status: 'declined',
    jobType: 'internship',
    jobLocation: 'Zheyuan',
  },
  {
    company: 'Hahn, Sanford and Goodwin',
    position: 'Product Engineer',
    status: 'interview',
    jobType: 'internship',
    jobLocation: 'Liushutun',
  },
  {
    company: 'Gottlieb LLC',
    position: 'Safety Technician III',
    status: 'pending',
    jobType: 'part-time',
    jobLocation: 'Jingmen',
  },
  {
    company: 'Weissnat LLC',
    position: 'Data Coordiator',
    status: 'declined',
    jobType: 'part-time',
    jobLocation: 'Néa Kíos',
  },
  {
    company: 'Schneider and Sons',
    position: 'Staff Scientist',
    status: 'declined',
    jobType: 'full-time',
    jobLocation: 'Wadusari',
  },
  {
    company: 'Orn Inc',
    position: 'Senior Sales Associate',
    status: 'declined',
    jobType: 'full-time',
    jobLocation: 'Dmitriyevka',
  },
  {
    company: 'Mraz, Weimann and Parisian',
    position: 'Information Systems Manager',
    status: 'declined',
    jobType: 'full-time',
    jobLocation: 'Tshela',
  },
  {
    company: 'Cremin, Durgan and Schmitt',
    position: 'Project Manager',
    status: 'pending',
    jobType: 'internship',
    jobLocation: 'Weton',
  },
  {
    company: 'Batz, Bruen and Miller',
    position: 'Human Resources Manager',
    status: 'interview',
    jobType: 'remote',
    jobLocation: 'Pandangan Kulon',
  },
  {
    company: 'Denesik Group',
    position: 'Administrative Officer',
    status: 'interview',
    jobType: 'part-time',
    jobLocation: 'Pergamos',
  },
  {
    company: 'Jaskolski-Senger',
    position: 'VP Sales',
    status: 'pending',
    jobType: 'remote',
    jobLocation: 'Svyetlahorsk',
  },
  {
    company: 'Kihn-Roberts',
    position: 'Software Test Engineer III',
    status: 'pending',
    jobType: 'full-time',
    jobLocation: 'Karangtengah',
  },
];

export default mockJobsData;
